var chart = d3.select("body").append("svg")
    .attr("class", "chart")
    .attr("width", 400)
    .attr("height", 400)
    .append("g")
    .attr("transform", "translate(200,200)")
    .append("path")
    .attr("d",
            d3.svg.arc()
            .innerRadius(0)
            .outerRadius(100)
            .startAngle(3/4 * Math.PI)
            .endAngle(9/4 * Math.PI)
            ({})
    )
